apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-02
  namespace: airflow2
  labels:
    app: airflow-logs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  resources:
    requests:
      storage: 10Gi